### ISSUE TITLE
file too large! status

### ISSUE THREAD

**Issue by triple1c86** [TSDARKNESS/BatchSubtitlesConverter#1]
yep exactly that.
put a about 25mb .sup file to convert. 
in the status it just say file too large.
![file too large](https://user-images.githubusercontent.com/2044519/46216230-af9fb400-c371-11e8-80b0-a19df3ab3bb6.jpg)

**Comment by TSDARKNESS** [comment]
It should works now in the pre-release [v2.6](https://github.com/TSDARKNESS/BatchSubtitlesConverter/releases/tag/2.6) by Editing the OCR Engine options under the Misc menu.
